<a href="https://colab.research.google.com/github/Anuj-Main/DataScienceProgramming/blob/main/NumPyCoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 **NumPy Coding**


In [22]:
import numpy as np
numpy_array=np.array([[1,2,3],[4,5,6]])
print(numpy_array)

[[1 2 3]
 [4 5 6]]


In [23]:
NP1=np.array([[1,3],[4,5]])
NP2=np.array([[3,4],[5,7]])
MNP=NP1@NP2
print(MNP)

[[18 25]
 [37 51]]


In [24]:
MNP2=NP1*NP2
print(MNP2)

[[ 3 12]
 [20 35]]


In [25]:
MNP3=np.dot(NP1,NP2)
print(MNP3)

[[18 25]
 [37 51]]


In [26]:
MNP4=np.multiply(NP1,NP2)
print(MNP4)

[[ 3 12]
 [20 35]]


In [27]:
sum=NP1+NP2
print(sum)

[[ 4  7]
 [ 9 12]]


In [28]:
sub=NP1-NP2
print(sub)

[[-2 -1]
 [-1 -2]]


In [29]:
sub1=np.subtract(NP1,NP2)
print(sub1)

[[-2 -1]
 [-1 -2]]


In [33]:
sum1=np.sum(NP1)
print(sum1)

13


In [35]:
add_array=NP1+3
print(add_array)

[[4 6]
 [7 8]]


In [36]:
NP3=np.array([[3,4]])
Add_Array=NP1+NP3
print(Add_Array)

[[4 7]
 [7 9]]


In [37]:
D=np.divide([12,14,16],5)
print(D)

[2.4 2.8 3.2]


In [38]:
D=np.floor_divide([12,14,16],5)
print(D)

[2 2 3]


In [39]:
sq_root=np.math.sqrt(10)
print(sq_root)

3.1622776601683795


**Normal and Uniform Distribution**

In [40]:
Normal_Dist=np.random.standard_normal((3,4))
print(Normal_Dist)

[[ 0.06190893 -1.25026995 -1.45915928  2.07897382]
 [-0.84937084  0.26385822 -0.91742714  0.88316879]
 [ 0.33878049 -0.83254361  0.3586431   0.88407002]]


In [42]:
Uniform_Dist=np.random.uniform(1,12,(3,4))
print(Uniform_Dist)

[[10.6103973  10.66278625  1.2638584   9.15442194]
 [ 8.56821051 11.26046968  7.00857803 10.52178853]
 [ 2.48241937 10.58978961  9.95304112  5.75996705]]


In [45]:
Random_intarray=np.random.randint(1,50,(2,5))
print(Random_intarray)

[[11 44  2 36 10]
 [ 7 23 36 37 34]]


In [46]:
Random_floatarray=np.random.rand(1,50,(2,5))
print(Random_floatarray)

TypeError: ignored