<a href="https://colab.research.google.com/github/Anuj-Main/DataScienceProgramming/blob/main/NumPyCoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy Coding


In [3]:
import numpy as np
numpy_array=np.array([[1,2,3],[4,5,6]])
print(numpy_array)

[[1 2 3]
 [4 5 6]]


In [4]:
NP1=np.array([[1,3],[4,5]])
NP2=np.array([[3,4],[5,7]])
MNP=NP1@NP2
print(MNP)

[[18 25]
 [37 51]]


In [5]:
MNP2=NP1*NP2
print(MNP2)

[[ 3 12]
 [20 35]]


In [7]:
MNP3=np.dot(NP1,NP2)
print(MNP3)

[[18 25]
 [37 51]]


In [9]:
MNP4=np.multiply(NP1,NP2)
print(MNP4)

[[ 3 12]
 [20 35]]
