<a href="https://colab.research.google.com/github/Anuj-Main/DataScienceProgramming/blob/main/NumPyCoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 **NumPy Coding**


In [1]:
import numpy as np
numpy_array=np.array([[1,2,3],[4,5,6]])
print(numpy_array)

[[1 2 3]
 [4 5 6]]


In [2]:
NP1=np.array([[1,3],[4,5]])
NP2=np.array([[3,4],[5,7]])
MNP=NP1@NP2
print(MNP)

[[18 25]
 [37 51]]


In [3]:
MNP2=NP1*NP2
print(MNP2)

[[ 3 12]
 [20 35]]


In [4]:
MNP3=np.dot(NP1,NP2)
print(MNP3)

[[18 25]
 [37 51]]


In [5]:
MNP4=np.multiply(NP1,NP2)
print(MNP4)

[[ 3 12]
 [20 35]]


In [6]:
sum=NP1+NP2
print(sum)

[[ 4  7]
 [ 9 12]]


In [7]:
sub=NP1-NP2
print(sub)

[[-2 -1]
 [-1 -2]]


In [8]:
sub1=np.subtract(NP1,NP2)
print(sub1)

[[-2 -1]
 [-1 -2]]


In [9]:
sum1=np.sum(NP1)
print(sum1)

13


In [10]:
add_array=NP1+3
print(add_array)

[[4 6]
 [7 8]]


In [11]:
NP3=np.array([[3,4]])
Add_Array=NP1+NP3
print(Add_Array)

[[4 7]
 [7 9]]


In [12]:
D=np.divide([12,14,16],5)
print(D)

[2.4 2.8 3.2]


In [13]:
D=np.floor_divide([12,14,16],5)
print(D)

[2 2 3]


In [14]:
sq_root=np.math.sqrt(10)
print(sq_root)

3.1622776601683795


**Normal and Uniform Distribution**

In [15]:
Normal_Dist=np.random.standard_normal((3,4))
print(Normal_Dist)

[[ 1.95641550e-01  2.41549111e+00  8.42166581e-01 -4.69989143e-01]
 [-1.81239563e-01  1.99694437e-04  1.46562697e+00 -6.70798899e-01]
 [-1.51140634e+00 -1.23644183e+00  8.45309713e-01 -3.32496350e-01]]


In [16]:
Uniform_Dist=np.random.uniform(1,12,(3,4))
print(Uniform_Dist)

[[ 9.96551797  8.45227376 11.16628408  1.98670166]
 [ 9.42035616  1.82643373 10.24798142  5.30389187]
 [10.75031315  2.44967138 10.85515957  3.86440683]]


In [17]:
Random_intarray=np.random.randint(1,50,(2,5))
print(Random_intarray)

[[15  8 36  5 12]
 [19 27 35 39 47]]


**Generate Random Zeroes and Random Numbers**



In [25]:
Random_Ze=np.zeros((3,4))
print(Random_Ze)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [26]:
Random_1=np.ones((3,4))
print(Random_1)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


**Filter the Array**

In [27]:
Filter_Array=np.logical_and(Random_intarray>30,Random_intarray<50)
print(Filter_Array)

[[False False  True False False]
 [False False  True  True  True]]


In [28]:
Filter_Random_Array=Random_intarray[Filter_Array]
print(Filter_Random_Array)

[36 35 39 47]
