<a href="https://colab.research.google.com/github/Anuj-Main/DataScienceProgramming/blob/main/NumPyCoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Coding


In [136]:
import numpy as np
Numpy_Array=np.array([[1,2,3],[4,5,6]])
print(Numpy_Array)

[[1 2 3]
 [4 5 6]]


**Simple Mathematics**

In [137]:
NP1=np.array([[1,3],[4,5]])
NP2=np.array([[3,4],[5,7]])
MNP=NP1@NP2
print(MNP)

[[18 25]
 [37 51]]


In [138]:
MNP2=NP1*NP2
print(MNP2)

[[ 3 12]
 [20 35]]


In [139]:
MNP3=np.dot(NP1,NP2)
print(MNP3)

[[18 25]
 [37 51]]


In [140]:
MNP4=np.multiply(NP1,NP2)
print(MNP4)

[[ 3 12]
 [20 35]]


In [141]:
sum=NP1+NP2
print(sum)

[[ 4  7]
 [ 9 12]]


In [142]:
sub=NP1-NP2
print(sub)

[[-2 -1]
 [-1 -2]]


In [143]:
sub1=np.subtract(NP1,NP2)
print(sub1)

[[-2 -1]
 [-1 -2]]


In [144]:
sum1=np.sum(NP1)
print(sum1)

13


In [145]:
add_array=NP1+3
print(add_array)

[[4 6]
 [7 8]]


In [146]:
NP3=np.array([[3,4]])
Add_Array=NP1+NP3
print(Add_Array)

[[4 7]
 [7 9]]


In [147]:
D=np.divide([12,14,16],5)
print(D)

[2.4 2.8 3.2]


In [148]:
D=np.floor_divide([12,14,16],5)
print(D)

[2 2 3]


In [149]:
sq_root=np.math.sqrt(10)
print(sq_root)

3.1622776601683795


**Normal and Uniform Distribution**

In [150]:
Normal_Dist=np.random.standard_normal((3,4))
print(Normal_Dist)

[[-1.70273266 -0.12896247  1.26617567 -0.78991636]
 [-0.92013154  0.54384006  0.26273968  0.89980273]
 [ 1.16922766  0.12455946  3.08370044  0.18605726]]


In [151]:
Uniform_Dist=np.random.uniform(1,12,(3,4))
print(Uniform_Dist)

[[ 4.80933523 10.56379407  6.4194418   1.71304903]
 [10.13537069  4.09002079  2.41761241  6.28290906]
 [ 8.87700793  7.7042848   7.08167866  9.14604532]]


In [152]:
Random_intarray=np.random.randint(1,50,(2,5))
print(Random_intarray)

[[44 17 32 47 29]
 [22 18 18 18 14]]


**Generate Random Zeroes and Random Numbers**



In [153]:
Random_Ze=np.zeros((3,4))
print(Random_Ze)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [154]:
Random_1=np.ones((3,4))
print(Random_1)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


**Filter the Array**

In [155]:
Filter_Array=np.logical_and(Random_intarray>30,Random_intarray<50)
print(Filter_Array)

[[ True False  True  True False]
 [False False False False False]]


In [156]:
Filter_Random_Array=Random_intarray[Filter_Array]
print(Filter_Random_Array)

[44 32 47]


**Statistical Part of NumPy**

In [157]:
Statistic_Data=np.array([1,2,3,4,5,6])
print(Statistic_Data)

[1 2 3 4 5 6]


In [158]:
Mean_Statistic_Data=np.mean(Statistic_Data)
print(Mean_Statistic_Data)

3.5


In [159]:
Median_Statistic_Data=np.median(Statistic_Data)
print(Median_Statistic_Data)

3.5


In [160]:
Variance_Statistic_Data=np.var(Statistic_Data)
print(Variance_Statistic_Data)

2.9166666666666665


In [161]:
SDeviation_Statistic_Data=np.std(Statistic_Data)
print(SDeviation_Statistic_Data)

1.707825127659933


**For More Column and Rows**

In [162]:
Variance_Numpy_Array=np.var(Numpy_Array)
print(Variance_Numpy_Array)

2.9166666666666665


In [163]:
Variance_Numpy_Array=np.var(Numpy_Array,axis=1)
print(Variance_Numpy_Array)

[0.66666667 0.66666667]


In [164]:
Variance_Numpy_Array2=np.var(Numpy_Array,axis=0)
print(Variance_Numpy_Array2)

[2.25 2.25 2.25]


#End of NumPy