<a href="https://colab.research.google.com/github/Anuj-Main/DataScienceProgramming/blob/main/PandasCoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas Coding

In [34]:
import pandas as pd

**Series**

In [35]:
AGE = pd.Series([10, 20, 30, 40, 50], index=['Age1', 'Age2', 'Age3', 'Age4', 'Age5'])
print(Age)

A1    10
A2    20
A3    30
A4    40
A5    50
dtype: int64


In [36]:
Age_call=AGE.Age5
print(Age_call)

50


In [37]:
Filter_Age=Age[Age>30]
print(Filter_Age)

A4    40
A5    50
dtype: int64


Change the indexes

In [38]:
Age.index=['A1','A2', 'A3', 'A4', 'A5']
print(Age)

A1    10
A2    20
A3    30
A4    40
A5    50
dtype: int64


**DataFrames**

In [39]:
import numpy as np
Df=np.array([[40,48,36,42,27],[29,35,25,46,45],[33,41,16,47,22],[32,19,39,42,45]])
print(Df)

[[40 48 36 42 27]
 [29 35 25 46 45]
 [33 41 16 47 22]
 [32 19 39 42 45]]


In [44]:
Data_Set=pd.DataFrame(Df)
print(Data_Set)

    0   1   2   3   4
0  40  48  36  42  27
1  29  35  25  46  45
2  33  41  16  47  22
3  32  19  39  42  45


In [47]:
Data_Set=pd.DataFrame(Df,index=['S1','S2','S3','S4'],columns=['Physics','Chemistry','Maths','English','Hindi'])
print(Data_Set)

    Physics  Chemistry  Maths  English  Hindi
S1       40         48     36       42     27
S2       29         35     25       46     45
S3       33         41     16       47     22
S4       32         19     39       42     45


In [48]:
Data_Set['Bio']=[28,27,39,40]
print(Data_Set)

    Physics  Chemistry  Maths  English  Hindi  Bio
S1       40         48     36       42     27   28
S2       29         35     25       46     45   27
S3       33         41     16       47     22   39
S4       32         19     39       42     45   40
