<a href="https://colab.research.google.com/github/Anuj-Main/DataScienceProgramming/blob/main/PandasCoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas Coding

In [4]:
import pandas as pd

**Series**

In [5]:
Age = pd.Series([10, 20, 30, 40, 50], index=['Age1', 'Age2', 'Age3', 'Age4', 'Age5'])
print(Age)

Age1    10
Age2    20
Age3    30
Age4    40
Age5    50
dtype: int64


In [6]:
Age_call=AGE.Age5
print(Age_call)

50


In [7]:
Filter_Age=Age[Age>30]
print(Filter_Age)

Age4    40
Age5    50
dtype: int64


Change the indexes

In [8]:
Age.index=['A1','A2', 'A3', 'A4', 'A5']
print(Age)

A1    10
A2    20
A3    30
A4    40
A5    50
dtype: int64


**DataFrames**

In [9]:
import numpy as np
Df=np.array([[40,48,36,42,27],[29,35,25,46,45],[33,41,16,47,22],[32,19,39,42,45]])
print(Df)

[[40 48 36 42 27]
 [29 35 25 46 45]
 [33 41 16 47 22]
 [32 19 39 42 45]]


In [10]:
Data_Set=pd.DataFrame(Df)
print(Data_Set)

    0   1   2   3   4
0  40  48  36  42  27
1  29  35  25  46  45
2  33  41  16  47  22
3  32  19  39  42  45


In [11]:
Data_Set=pd.DataFrame(Df,index=['S1','S2','S3','S4'],columns=['Physics','Chemistry','Maths','English','Hindi'])
print(Data_Set)

    Physics  Chemistry  Maths  English  Hindi
S1       40         48     36       42     27
S2       29         35     25       46     45
S3       33         41     16       47     22
S4       32         19     39       42     45


In [12]:
Data_Set['Bio']=[28,27,39,40]
print(Data_Set)

    Physics  Chemistry  Maths  English  Hindi  Bio
S1       40         48     36       42     27   28
S2       29         35     25       46     45   27
S3       33         41     16       47     22   39
S4       32         19     39       42     45   40


In [13]:
Row_A=Data_Set.loc['S1']
print(Row_A)

Physics      40
Chemistry    48
Maths        36
English      42
Hindi        27
Bio          28
Name: S1, dtype: int64


In [15]:
S4=Data_Set.loc['S4']['Bio']
print(S4)

40


Now we are using iloc to get specific details because in loc function we can only use alphabets or index names not the indexes.

In [16]:
individualS3=Data_Set.iloc[2][3]
print(individualS3)

47


In [17]:
All_Rows=Data_Set.iloc[:,2]
print(All_Rows)

S1    36
S2    25
S3    16
S4    39
Name: Maths, dtype: int64


In [18]:
Filtered_Columns=Data_Set.iloc[:,1:3]
print(Filtered_Columns)

    Chemistry  Maths
S1         48     36
S2         35     25
S3         41     16
S4         19     39


Removing the Column or Rows (Drop Function)

In [19]:
Re_move=Data_Set.drop('Hindi',axis=1)
print(Re_move)

    Physics  Chemistry  Maths  English  Bio
S1       40         48     36       42   28
S2       29         35     25       46   27
S3       33         41     16       47   39
S4       32         19     39       42   40


In [21]:
print(Data_Set)

    Physics  Chemistry  Maths  English  Hindi  Bio
S1       40         48     36       42     27   28
S2       29         35     25       46     45   27
S3       33         41     16       47     22   39
S4       32         19     39       42     45   40


If you want to change the real data set you have to use all these function under data set.
Example = Data_Set=Data_Set.functionname()

In [22]:
Re_place=Data_Set.replace(16,35)
print(Re_place)

    Physics  Chemistry  Maths  English  Hindi  Bio
S1       40         48     36       42     27   28
S2       29         35     25       46     45   27
S3       33         41     35       47     22   39
S4       32         19     39       42     45   40


Now change the multiple value

In [23]:
Multi_Value=Data_Set.replace({27:32,35:42})
print(Multi_Value)

    Physics  Chemistry  Maths  English  Hindi  Bio
S1       40         48     36       42     32   28
S2       29         42     25       46     45   32
S3       33         41     16       47     22   39
S4       32         19     39       42     45   40


If we have large data then we use head and tail

In [26]:
Data_Set.head()

Physics  Chemistry  Maths  English  Hindi  Bio
S1       40         48     36       42     27   28
S2       29         35     25       46     45   27
S3       33         41     16       47     22   39
S4       32         19     39       42     45   40

In [27]:
Data_Set.head(2)

Physics  Chemistry  Maths  English  Hindi  Bio
S1       40         48     36       42     27   28
S2       29         35     25       46     45   27

In [29]:
Data_Set.tail(2)

Physics  Chemistry  Maths  English  Hindi  Bio
S3       33         41     16       47     22   39
S4       32         19     39       42     45   40

Sorting the values in Rows and Columns

In [30]:
Data_Set.sort_values('Maths',ascending=True)

Physics  Chemistry  Maths  English  Hindi  Bio
S3       33         41     16       47     22   39
S2       29         35     25       46     45   27
S1       40         48     36       42     27   28
S4       32         19     39       42     45   40

In [32]:
Data_Set.sort_index(axis=0,ascending=False)

Physics  Chemistry  Maths  English  Hindi  Bio
S4       32         19     39       42     45   40
S3       33         41     16       47     22   39
S2       29         35     25       46     45   27
S1       40         48     36       42     27   28